### ISSUE TITLE
Hi. Problems building "KID" 

### ISSUE THREAD

**Issue by pervrosen** [monoid-gmbh/kid#1]
First I had to use "old" GHC-8.10.4 to even build your [https://github.com/yveshauser/quandl-api-v3](https://github.com/yveshauser/quandl-api-v3) . However after successfully doing that I fail on building kid. 

```
$ cabal build
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - kid-0.1.0.0 (lib) (first run)
 - kid-0.1.0.0 (exe:kid-exe) (first run)
Preprocessing library for kid-0.1.0.0..
Building library for kid-0.1.0.0..
<command line>: does not exist: src/fut/Calculation.c
Error: cabal: Failed to build kid-0.1.0.0 (which is required by exe:kid-exe
from kid-0.1.0.0).

$ cabal build kid
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - kid-0.1.0.0 (lib) (first run)
Preprocessing library for kid-0.1.0.0..
Building library for kid-0.1.0.0..
<command line>: does not exist: src/fut/Calculation.c
Error: cabal: Failed to build kid-0.1.0.0.
```
After searching a while via google I found out that haskell->C was not really supported any more. Perhaps you could update your build instructions for a successful build? I also have CUDA capabilities with 2*RTX3090 cards. 

(
2. Also, I do not really understand how to relate "kid-annex" to "kid". Any instruction on that? Or is the build instructions in the README complete in kid-annex in regards to use the kid-annex in kid?
3. Not related to this but still relevant for me is that I want to use my own local time series, How is that possible?
)

**Comment by yveshauser** [comment]
The simulation engine is located in [kid-annexes](https://github.com/monoid-gmbh/kid-annexes). I need to provide a proper integration of this dependency. Currently there is just a [Makefile](src/fut/Makefile) that for doing this manually

**Comment by yveshauser** [comment]
For your third point above, I opened an extra ticket: #2

**Comment by yveshauser** [comment]
Added instructions to the top level README and another ticket to address the issue properly, see #3
